let &rtp = expand('$DOTDIR/vim').','.&rtp
call plug#begin(expand('$DOTDIR/vim/plugged'))

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'chriskempson/base16-vim'
Plug 'editorconfig/editorconfig-vim'

call plug#end()

filetype plugin indent on
syntax on

" colors and terminal
set t_Co=256
set background=dark
silent! color base16-tomorrow-night
set noexrc " disable local exrc/vimrc foo
let mapleader = "," " switch the leader to something more reachable
" enable line numbers but allow them to be easily toggled
set number
nmap <C-N><C-N> :set invnumber<CR>
set backspace=indent,eol,start " enhance backspace
" show vim status bar and ruler
set laststatus=2
set ruler
set encoding=utf-8
" Whitespace stuff
set nowrap " don't wrap lines
set tabstop=2 " a tab should be four spaces
set shiftwidth=2 " indents should also use 4 space base
set softtabstop=2 " to be safe, soft tabs at 4 too
set expandtab " no tabs!
set smarttab
" highlighting unprintables
set list listchars=tab:\ \ ,trail:·
" Searching
set nohlsearch " don't do the highlight search thing after we've searched
set incsearch " but please highlight search as we type
set ignorecase " case insensitive
set smartcase " unless we look like we want case-sensitive
" Use modeline overrides
set modeline
set modelines=3

" Directories for swp files
let backup_folder = "$DOTDIR/vim/backup"
if !isdirectory(expand(backup_folder))
    call mkdir(expand(backup_folder), "p")
endif
let &backupdir = expand(backup_folder)
let &directory = &backupdir

" Show (partial) command in the status line
set showcmd

set mouse=a

au BufNewFile,BufRead *.gradle setf groovy

au FileType go set sw=8 ts=8 sts=8 noet
let g:go_auto_type_info = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_interfaces = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

if has('python3')
    silent! python3 << EOF
try:
    from powerline.vim import setup as powerline_setup
    powerline_setup()
    del powerline_setup
except ImportError as e:
    pass
EOF
endif

" split nav conveniences
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set splitbelow
set splitright


" Include user's local vim config
if filereadable(expand("$DOTLOCAL/vim/vimrc"))
  source $DOTLOCAL/vim/vimrc
endif

" vim: ft=vim ts=4 sts=4 sw=4 expandtab
