#!/bin/bash

export DOTDIR="${HOME}"/.dotfiles
shopt -s nullglob

for __profile_d in /etc/profile.d/*; do
  . "${__profile_d}"
done
unset __profile_d

for __common_cfg in "${DOTDIR}"/shell/common/*; do
  . "${__common_cfg}"
done
unset __common_cfg

# interactive-only
if [[ $- != *i* ]]; then
  return
fi

## Config
set -o emacs
shopt -s autocd
shopt -s cdspell
shopt -s checkhash
shopt -s checkwinsize
shopt -s cmdhist
shopt -s dirspell
shopt -s extglob
shopt -s globstar
shopt -s histappend
shopt -s histreedit
shopt -s histverify
shopt -s lithist


## History
HISTCONTROL=ignoreboth:erasedups
HISTFILE=~/.bash_history
HISTSIZE=10000
HISTFILESIZE=10000
unset MAILCHECK
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"


## command-not-found
command_not_found_handle() {
  if [[ -x /usr/lib/command-not-found ]]; then
    /usr/lib/command-not-found -- "$1"
    return $?
  else
    printf '%s: command not found\n' "$1" >&2
    return 127
  fi
}


## Prompt
. "${SHELLDOTDIR}"/bash/prompt_basic

if [[ -r ${DOTLOCAL}/shell/bashrc ]]; then
  . "${DOTLOCAL}"/shell/bashrc
fi

if [[ ${BASH_VERSINFO[0]} == 4 && ${BASH_VERSINFO[1]} < 4 ]]; then
  # bash 4.3, for some reason, nullglob on causes tab completion to break
  shopt -u nullglob
fi
