#!/bin/bash

shmain() {
    local -r flags_file="${HOME}/.config/chrome-flags.conf"
    local -a chrome_user_flags
    if [[ -v WAYLAND_DISPLAY || ${XDG_SESSION_TYPE:-} == wayland ]]; then
      chrome_user_flags+=( --enable-wayland-server )
    fi
    if [[ -r ${flags_file} ]]; then
        local line
        while read -r line; do
            [[ ${line} == *#* ]] && continue
            chrome_user_flags+=( "${line}" )
        done < "${flags_file}"
        export CHROME_USER_FLAGS="${chrome_user_flags[*]}"
    fi
    printenv | sort > /tmp/$$.env
    exec "/usr/bin/google-chrome" "${chrome_user_flags[@]}" "$@"
}

shmain "$@"
