(
  autoload -Uz zrecompile

  declare -a files=(
    "${ZDOTDIR}"/.zcompdump
    "${ZDOTDIR}"/.zshrc
    "${ZDOTDIR}"/completion
    "${ZDOTDIR}"/prompt/all.zsh
    "${ZDOTDIR}"/prompt/themes/*
  )
  for file in "${files[@]}"; do
    if zrecompile -pq "${file}"; then
      rm -f "${file}.zwc.old"
    fi
  done
) &!
