#!/bin/zsh

## common configuration
source "${ZDOTDIR}"/common.zsh

## the remainder is interactive-only
if [[ ! -o interactive ]]; then
    return
fi

## Completion config
source "${ZDOTDIR}"/completion.zsh

## History config
source "${ZDOTDIR}"/history.zsh

## zle/editor config
source "${ZDOTDIR}"/editor.zsh

## prompt/theming config
source "${ZDOTDIR}"/themes.zsh

## miscellaneous config
source "${ZDOTDIR}"/misc.zsh

## local zshrc
if [[ -r ${ZDOTLOCAL}/zshrc ]]; then
    source "${ZDOTLOCAL}"/zshrc
fi

asdf_zshrc="${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"
if [[ -r ${asdf_zshrc} ]]; then
    source "${asdf_zshrc}"
fi
