#!/usr/bin/env bash

ggh() {
  if git rev-parse --is-inside-work-tree &> /dev/null; then
    cd "$(git rev-parse --show-toplevel)"
  else
    echo "$(pwd)" is not a git repository" >&2
    return 1
  fi
}
