local -a _config_sections
_config_sections=( pre_zshrc config editor completion aliases prompt ext post_zshrc )

local _config_dir
local _config_section
local _config_file

for _config_section in ${_config_sections[@]}; do
  for _config_dir in ${_zsh_config_dirs[@]}; do
    for _config_file in ${_config_dir}/${_config_section}/${^_zsh_config_flavors}.zsh(N); do
      source ${_config_file}
    done
  done
done

unset _config_dir _config_sections _config_section _config_file

# vim: filetype=zsh:ts=2:sw=2:expandtab
