local -a _config_sections
_config_sections=( config editor completion aliases prompt ext )

local _config_dir
local _config
for _config_dir in ${_zsh_config_dirs}; do
  for _config in ${_config_dir}/${^_config_sections}/${^_zsh_config_flavors}.zsh(N) ; do
    source ${_config}
  done
done

unset _config _config_dir _config_sections

# vim: filetype=zsh:ts=2:sw=2:expandtab
