#!/bin/bash

export SHELLDOTDIR="${DOTDIR}/shell"
export DOTBIN="${DOTDIR}/bin"
export DOTLOCAL="${HOME}/.local"
export DOTLOCALBIN="${DOTLOCAL}/bin"
export SHELLDOTLOCAL="${DOTLOCAL}/shell"
export DOTCONFIG="${HOME}/.config"

export MYVIMRC=${DOTDIR}/vim/vimrc
export VIMINIT="so ${MYVIMRC}"
export EDITOR="vim"
export VISUAL="vim"

export PAGER="less"
export LESS="giwRM"
export SYSTEMD_LESS="${LESS}K"
if [[ -x /usr/bin/lesspipe ]]; then
  export LESSOPEN="| /usr/bin/lesspipe %s"
  export LESSCLOSE="/usr/bin/lesspipe %s %s"
fi

export TZ="PST8PDT"

export WD="${HOME}/work"
export WD_STASH="${WD}/stash"
export WD_GITHUB="${WD}/github"

if [[ -r ${DOTLOCAL}/shell/env ]]; then
  # shellcheck disable=SC1091
  . "${DOTLOCAL}"/shell/env
fi
