#!/usr/bin/env bash

declare -ax path=(
  "${DOTLOCAL}"/bin
  "${HOME}"/bin
  /usr/local/bin
  /usr/bin
  /bin
  /usr/local/sbin
  /usr/sbin
  /sbin
  /snap/bin
  /usr/games
)

declare -ax manpath=(
  /usr/local/share/man
  /usr/share/man
)

if [[ -r ${DOTLOCAL}/shell/path ]]; then
  . "${DOTLOCAL}"/shell/path
fi

if [[ -n ${ZSH_NAME:-} ]]; then
  declare -U path
  declare -U manpath
  return
fi

if [[ -n ${BASH:-} ]]; then
  setpath() {
    printf -v PATH '%s:' "${path[@]}"
    export PATH="${PATH%:}"
    printf -v MANPATH '%s:' "${manpath[@]}"
    export MANPATH="${MANPATH%:}"
    return
  }
  setpath
fi
