#!/bin/bash

alias vi=vim
alias ls='ls -F --color=auto'
alias sa='ssh-add ${HOME}/.ssh/id_rsa'
alias sl='ssh-add -l'
alias grpo='git remote prune origin'
alias grep='grep --color=auto'

# zsh-only
if [[ -n ${ZSH_NAME:-} ]]; then
  alias help='run-help'
fi

if [[ -r ${DOTLOCAL}/shell/aliases ]]; then
  . "${DOTLOCAL}"/shell/aliases
fi
