#!/bin/bash

funcdirs=(
  "${DOTLOCAL}"/shell/functions
  "${SHELLDOTDIR}"/functions
)

if [[ -n ${ZSH_NAME:-} ]]; then
  fpath=(
    "${DOTLOCAL}/shell/zsh/functions"
    "${SHELLDOTDIR}/zsh/functions"
    "${funcdirs[@]}"
    "${fpath[@]}"
  )
  declare -U fpath
  if [[ -r ${DOTLOCAL}/shell/zsh/fpath.zsh ]]; then
    # shellcheck disable=SC1090
    source "${DOTLOCAL}"/shell/zsh/fpath.zsh
  fi
fi

if [[ -n ${BASH:-} ]]; then
  # shellcheck source=../bash/autoload
  . "${SHELLDOTDIR}"/bash/autoload
  export FPATH=(
    "${DOTLOCAL}/shell/bash/functions"
    "${SHELLDOTDIR}/bash/functions"
    "${funcdirs[@]}"
  )
  if [[ -r ${DOTLOCAL}/shell/bash/fpath.bash ]]; then
    # shellcheck disable=SC1090
    source "${DOTLOCAL}"/shell/bash/fpath.bash
  fi
fi

for funcdir in "${funcdirs[@]}"; do
  [[ -d ${funcdir} ]] || continue
  for funcfile in "${funcdir}"/*; do
    [[ -f ${funcfile} ]] || continue
    funcname="${funcfile##*/}"
    autoload "${funcname}"
  done
done
unset funcdirs funcname funcfile
